# top level stuff
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# site settings
url: "http://www.sana-ajani.me/"
baseurl: ""
title: sana-ajani.me
author: Sana Ajani
description: Personal blog and resume
avatar: sana.png
email: sajani6@gatech.edu.com
github: sana-ajani
twitter: sana_ajani
linkedin: sanaajani
timezone: America/New_York
medium: sanaajani
disqus: sana-ajani.me
google_analytics: UA-87591804-1


# needed for travis-ci build
exclude: [vendor]
